name: Trigger Build
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Test Report
        path: playwright-report/
        retention-days: 30

    - name: Send email notification
      uses: dawidd6/action-send-mail@v1
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Playwright Test Report for ${{ github.repository}}"
        from: foysal134038@gmail.com 
        to: shakhawat.swe@gmail.com
        body: |
            Hi,

            Here is the test report for the latest commit on the main branch.

            [Include the content or link to your test report here.]

            Best regards,
            Rehan Khan

